### ISSUE TITLE
[Bug]: 引入 ElementUI 后报 require is not defined 

### ISSUE THREAD

**Issue by Ttou** [web-infra-dev/rsbuild#958]
### 版本信息

```sh
System:
    OS: macOS 14.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 244.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Safari: 17.2
  npmPackages:
    @rsbuild/core: ^0.2.4 => 0.2.4 
    @rsbuild/plugin-vue2: ^0.2.4 => 0.2.4
```

### 问题详情

1. 引入 ElementUI

```ts
import Vue from 'vue'

import App from './App.vue'
import ElementUI from 'element-ui'

Vue.config.productionTip = false

Vue.use(ElementUI);

new Vue({ render: h => h(App) }).$mount('#app')
```

2. 启动项目后，浏览器空白，控制台标签下报 require is not defined 

![image](https://github.com/web-infra-dev/rsbuild/assets/4298437/af8fdc48-5082-4013-9e78-4607a1cd3219)

### 复现链接

https://github.com/Ttou/rsbuild-require-issue

### 复现步骤

1. pnpm dev
2. 浏览器控制台报错：Uncaught ReferenceError: require is not defined

**Comment by 9aoy** [comment]
Fixed: https://github.com/web-infra-dev/rspack/issues/4997

Need to wait for rspack to release the next version, or use rspack canary version (`0.4.3-canary-45d565f-20231215022203`) to test it.

**Comment by chenjiahan** [comment]
Fixed in the latest version

**Comment by witalobenicio** [comment]
I'm still facing this issue with latest versions @chenjiahan

**Comment by chenjiahan** [comment]
@witalobenicio Can you submit a new issue and provide a reproduce repo?
